theme: jekyll-theme-leap-day
title: Techniekdag 2018 - Yoast pretpark
description: Tijdens het afgelopen Techniekdag, heeft Yoast jou gevraagd om te helpen met het opbouwen van een pretpark in het programma Scratch! Op deze dag heb je ook een kaartje ontvangen waarop jouw unieke code staat zodat je jouw pretpark hier kunt downloaden.
